import type { Metadata } from "next";
import Link from 'next/link';
import "./globals.css";
import ReduxProvider from '../components/ReduxProvider';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <nav>
            <Link href="/">Home</Link> | 
            <Link href="/posts">Posts</Link> | 
            <Link href="/about">About</Link> | 
            <Link href="/contact">Contact</Link>
          </nav>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
